
services:
  blog-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-site-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_SERVER_URI=${VITE_SERVER_URI}
      - VITE_SOCKET_URI=${VITE_SOCKET_URI}