name: blog-site-deploy

on:
  push:
    branches:
      - frontend
  pull_request:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: "self-hosted"

    steps:
      - name: Update system
        run: sudo apt update

      - name: Code-Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker compose build

      - name: Remove Docker Container -
        run: docker compose down || true

      - name: Docker Run
        run: docker compose up -d
        env:
          VITE_SERVER_URI: ${{ secrets.VITE_SERVER_URI }}
          VITE_SOCKET_URI: ${{ secrets.VITE_SOCKET_URI }}
      - name: Docker Clean
        run: docker system prune -af
